### ISSUE TITLE
[doc]The cluster context-current and the environment KUBECONFIG mistakes

### ISSUE THREAD

**Issue by Aisuko** [engineerd/setup-kind#19]
Hi, guys Thanks for developing the amazing `GithubAction`. It is totally good for our community. But I have been founding the issue below 

* The default context is `kind-kind`
* The environment name `KUBECONFIG` did not export by automation

The `ci.yaml` file

```
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ secrets.GO_VERSION }}
    - name: Create cluster using KinD
      uses: engineerd/setup-kind@v0.3.0
      with:
        version: "v0.7.0"
    - run: |
        kubectl cluster-info
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
```

The CI logs

![Screen Shot 2020-04-07 at 3 47 53 PM](https://user-images.githubusercontent.com/8053949/78643656-27478b00-78e7-11ea-96dd-cafbc7c10c2c.png)
