### ISSUE TITLE
Config file seems to fail, can't tell why.

### ISSUE THREAD

**Issue by rsliotta** [engineerd/setup-kind#23]
This is my config.  I basically commented everything out except nodes.
```
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  # apiServerAddress: "10.2.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
  #  podSubnet: "10.244.0.0/16"
  #  image: kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55
nodes:
- role: control-plane
- role: worker
- role: worker
```
Here is the error:

Creating cluster "kind" ...
ERROR: failed to create cluster: unknown kind  for apiVersion: kind.x-k8s.io/v1alpha4
##[error]The process '/opt/hostedtoolcache/kind/0.8.1/x64/kind' failed with exit code 1

Here is the action:
```
name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.4.0
      with:
          version: "v0.8.1"
          config: ".github/workflows/bob-cluster.yaml"
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
```
