### ISSUE TITLE
github action not working

### ISSUE THREAD

**Issue by frederikschaaf** [engineerd/setup-kind#248]
using the basic integration code:
```
name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
```

this happens on github actions:

```
Run engineerd/setup-kind@v0.5.0
downloading kind from https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
/usr/bin/chmod +x /home/runner/work/_temp/8d15fe11-b8f6-4172-b29c-e08b03283c58
Executing kind with args create,cluster,--name,kind,--wait,300s
/opt/hostedtoolcache/kind/0.7.0/x64/kind create cluster --name kind --wait 300s
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.17.0) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦 
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged 50fd0e98ffc6069965f0f629fca2730ed8c9f641f02fcd9dba6130cc5fb9e152 kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Error: The process '/opt/hostedtoolcache/kind/0.7.0/x64/kind' failed with exit code 1
```

Did I miss something?
