### ISSUE TITLE
Way of specifying kubernetes version

### ISSUE THREAD

**Issue by plumdog** [engineerd/setup-kind#35]
I would like to be able to have a CI workflow that tests against a set of kubernetes versions.

It would look something like:

```yaml
name: "Run linting and install charts"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        kubernetes-version:  # matrix of kubernetes versions
          - '1.18'
          - '1.19'
          - '1.20'  

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
        with:
          version: v3.3.0

       - name: Create kind cluster
         uses: helm/kind-action@v1.0.0
         with:
           version: ${{ matrix.kubernetes-version }}  # use the kubernetes-version. This is the feature I think I want

       - name: Run chart-testing (install)
         run: ct install --config ct.yaml --all
```

Is this something that I could already achieve somehow?
