### ISSUE TITLE
kind action failing for multi kubernetes tests

### ISSUE THREAD

**Issue by suramya-shah** [engineerd/setup-kind#38]
Hi I am using the following config in yaml
jobs:
```
  # Job to run change detection 1.16
  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest , ubuntu-18.04, ubuntu-20.04] 
        kindfile: [ 'kind21.yaml', 'kind20.yaml', 'kind.yaml' ] 
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4
      - name: Setup Kind Clutser
        uses: engineerd/setup-kind@v0.5.0
        with:
          config: ${{ matrix.kindfile }}
          version:  v0.11.0
```
but while testing kubectl my build fails with the following error:
`Unable to connect to the server: dial tcp: lookup kind-control-plane: Temporary failure in name resolution.`
