### ISSUE TITLE
Support KIND running inside container 

### ISSUE THREAD

**Issue by axsaucedo** [engineerd/setup-kind#40]
Currently we have KIND running in our Kubernetes CI, where KIND runs inside of a pod/container, which requires the following mounts with the node:
```
                volumeMounts:
                  - mountPath: /lib/modules
                    name: modules
                    readOnly: true
                  - mountPath: /sys/fs/cgroup
                    name: cgroup
                  - name: dind-storage
                    mountPath: /var/lib/docker
                securityContext:
                  privileged: true
                imagePullPolicy: Always
              volumes:
                - name: modules
                  hostPath:
                    path: /lib/modules
                    type: Directory
                - name: cgroup
                  hostPath:
                    path: /sys/fs/cgroup
                    type: Directory
                - name: dind-storage
                  emptyDir: {}
```

When running a KIND docker action inside a KIND enabled container (which works on kubernetes) such as:
```
...
    runs-on: ubuntu-18.04
    container: repo/container:tag
...
```
It seems to work when running it locally using `act` (https://github.com/nektos/act), but when running it on the github Actions worker, I get the error `Error: Kubernetes cluster unreachable: Get https://127.0.0.1:34221/version?timeout=32s: dial tcp 127.0.0.1:34221: connect: connection refused`.

The KIND cluster does seem to get correctly created, but the issue seems to mainly be that the cluster is not reachable. Is this an issue that you have come across before?

There would be a lot of advantages running KIND inside container, such as being able to have a replicatable environment from where to run the creation of resources, running the tests with pytest, etc.
